name: Build and deploy .NET Core application to Web App ImageUploadAPI

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: ImageUploadAPI
  AZURE_WEBAPP_PACKAGE_PATH: ImageAPI\publish
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: ImageAPI

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Restore Dependencies
        run: dotnet restore "${{ env.WORKING_DIRECTORY }}"

      - name: Build Application
        run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: Run Tests
        run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build

      - name: Publish Application
        run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deploy to Azure WebApp
        if: ${{ secrets.SECRET != '' }}
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.SECRET }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
